name: Cross Compile for MIPS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-mips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install MIPS cross-compiler
        run: sudo apt-get update && sudo apt-get install gcc-mipsel-linux-gnu binutils-mipsel-linux-gnu g++-multilib libc6-dev-i386

      - name: Compile C code for MIPS
        run: mipsel-linux-gnu-gcc -o http-redirect http-redirect.c -W -Wall -Wextra -pedantic -O2 -msoft-float -static -mfp32
        
      - name: check result
        run: pwd && ls -l 
        
      - name: Upload MIPS artifact
        uses: actions/upload-artifact@v4
        with:
          name: mips-binary
          path: |
            http-redirect
            # 此处填写你编译后生成的文件路径
            # 例如：
            # my_program
            # build/output/*