name: Cross Compile for MIPS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-mips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with dockcross (mips)
        uses: dockcross/dockcross@master
        with:
          image: mips
          args: |
            bash -c '
              set -ex
              # 编译你的C语言项目
              # 假设你的项目使用Makefile
              make
              # 你也可以直接调用交叉编译器
              # $CC -o my_program my_source.c
              pwd
              ls
            '

      - name: Upload MIPS artifact
        uses: actions/upload-artifact@v4
        with:
          name: mips-binary
          path: |
            http-redirect
            # 此处填写你编译后生成的文件路径
            # 例如：
            # my_program
            # build/output/*